### ISSUE TITLE
1.19.2-1.4.5 Spacing between Structures

### ISSUE THREAD

**Issue by ToastiMan** [craisinlord/IDAS#1]
Spacing between Structures is way too small, mostly 2-3 Structures spawn in a very close space

![2022-09-26_17 57 38](https://user-images.githubusercontent.com/102863578/192324498-9e9562d6-e662-473f-8214-457f724c0db6.png)

**Comment by littlepianist** [comment]
![2022-10-02_14 14 33](https://user-images.githubusercontent.com/75674050/193440748-5947b959-054c-4e4b-8959-5fcf952398c2.png)
they also sometimes detroy other structures

**Comment by craisinlord** [comment]
Thanks for reporting! Fixed in 1.4.6
