### ISSUE TITLE
License what?

### ISSUE THREAD

**Issue by Kasualix** [craisinlord/IDAS#10]
CurseForge: [ARR](https://www.cursef[orge.com/project/605375/license)
GitHub: [LGPL-3.0](https://github.com/craisinlord/IDAS/blob/master/LICENSE)
mods.toml: [ARR](https://github.com/craisinlord/IDAS/blob/d7b0da4ddce6bf37bc435b8415a4a4d47b86be40/src/main/resources/META-INF/mods.toml#L3)

**Comment by craisinlord** [comment]
whoops! yeah its meant to be ARR
