### ISSUE TITLE
Sporadic server crashes [1.19.2]

### ISSUE THREAD

**Issue by CameronJThomas** [craisinlord/IDAS#15]
Every so often my dedicated server is hanging and subsequently crashing. Having looked through the crash log, it appears to come back to the generation of IDAS maps for cartographers (see line ~107 of the crash log, where `com.craisinlord.integrated_api.misc.maptrades.StructureSpecificMaps$TreasureMapForEmeralds.getOffer` is invoked).

Could this be investigated? Also, is it possible to disable this feature of the pack entirely? Nobody on my server is particularly interested in maps, and they are quite resource intensive as they necessitate the generation of new chunks.

Let me know if any more info is needed.

[Crash Report.txt](https://github.com/craisinlord/IDAS/files/11790265/Crash.Report.txt)

**Comment by craisinlord** [comment]
Sorry for the late response! I typically check issues on Curse more frequently than here. 

This is because the game is looking for a structure far away. You can disable this feature of the mod using the config datapack and removing the trades
