### ISSUE TITLE
Server hanging issue - Incompatability with The Bumblezone

### ISSUE THREAD

**Issue by TheWisme** [craisinlord/IDAS#26]
There exists an issue when both The Bumblezone and Integrated Dungeons and Structures and its dependencies are loaded, and when trying to load specific chunks. If you try to load a chunk where an IDAS structure would spawn, there is a chance that the server will get caught trying to process a single tick. We're not sure which of the two is causing it or why, or even what specifically causes the issue, but to recreate follow the steps below.

1. Create a 1.20.1, Neoforge 47.1.101 instance with the most up to date versions of Intergrated Dungeons and Structures, Integrated API, Create, Quark, Zeta, Supplementaries, Moonlight Library, and The Bumblezone.
2. Create a world with the seed "6643873748131111404"
3. Teleport to the coordinates 860, 100 -250
4. Attempt to travel northeast about 150 blocks

Expected behavior: The chunks load as expected, with an IDAS castle structure in the loaded chunks

Actual behavior: The server hangs, and must be killed to exit.

I hope this helps you diagnose the issue.

**Comment by deadspidervenom** [comment]
I made a post with less detail as i did not know it was a bumblezone issue. As it fixed disabling IDAS.

https://github.com/craisinlord/IDAS/issues/25

**Comment by deadspidervenom** [comment]
After learning about it being bumblezone i did the same test as in my own issue (removing bumblezone) but with that mod. I investigated the building for anything weird basing my search on what was left of the castle in my issue. Only weird generation was this screenshot.

![2024-04-07_18 02 54](https://github.com/craisinlord/IDAS/assets/12871122/f275fdee-224c-43b2-9322-e90d6d68c282)

**Comment by TheWisme** [comment]
This issue has been solved by bumblezone as of about an hour ago. The issue turned out to be horses that spawned with owners upon worldgen.
