### ISSUE TITLE
IDAS causes an insane lag spike, related to villager trades

### ISSUE THREAD

**Issue by Malex21** [craisinlord/IDAS#3]
As the spark profiler says, 
https://spark.lucko.me/yaWoV8cLn9?hl=176
https://spark.lucko.me/ZjAvD4Rvme?hl=4871

IDAS has caused an insane lag spike, (45s and 316s, for 18 loaded villagers in the entire server) whenever the villager tries to update its trades.

**Comment by craisinlord** [comment]
This is because the villager maps search large distances until it finds rare idas structure. The only fixes would be changed the search distance or changing structure rarities. These are both configurable with the config data pack.
