### ISSUE TITLE
[1.18.2] Dedicated server crash

### ISSUE THREAD

**Issue by Proxwian** [craisinlord/IDAS#5]
[crash-2023-01-05_13.04.58-server.txt](https://github.com/craisinlord/IDAS/files/10352679/crash-2023-01-05_13.04.58-server.txt)
[crash-2023-01-04_20.35.45-server.txt](https://github.com/craisinlord/IDAS/files/10352680/crash-2023-01-04_20.35.45-server.txt)
[crash-2023-01-04_21.11.17-server.txt](https://github.com/craisinlord/IDAS/files/10352681/crash-2023-01-04_21.11.17-server.txt)

1-2 times a day server crashes with the same error:
java.lang.IllegalStateException: Missing key in ResourceKey[minecraft:root / minecraft:worldgen/configured_structure_feature]: ResourceKey[minecraft:worldgen/configured_structure_feature / idas:wizardtower]

Map is fully preloaded, so it seems to be crash when player enters some chunk with generated structure.

**Comment by craisinlord** [comment]
Fixed in 1.5.2. This was an issue with Cartographer villagers making maps to the wizard towers
