### ISSUE TITLE
[1.18.2] Beekeeper's house and Illager Fortress can generate on top of each other

### ISSUE THREAD

**Issue by brisingraerowing** [craisinlord/IDAS#8]
![2023-01-31_20 02 04](https://user-images.githubusercontent.com/250409/215919563-f9da2648-5043-4fc7-ad45-65700f22131d.png)

Looks like a structures to avoid entry got missed.

**Comment by craisinlord** [comment]
This was fixed a while back, I just never check this page, I check curse more
